/** \file param.h

Created automatically during compilation
from var.c. Do not edit. See Perl script
"varparser.pl" for details.
*/
extern	real	DT;
extern	real	SIGMA0;
extern	int	NINTERM;
extern	int	NTOT;
extern	char	OUTPUTDIR[512];
extern	char	OPENINNERBOUNDARY[512];
extern	char	ADVLABEL[512];
extern	char	TRANSPORT[512];
extern	char	DUSTDIFF[512];
extern	char	GASDCOUPLE[512];
extern	char	DUSTIMPLICIT[512];
extern	real	COUPLEINN;
extern	real	DUSTDIFFINN;
extern	real	PSize;
extern	char	PLANETCONFIG[512];
extern	real	MASSTAPER;
extern	char	GRIDSPACING[512];
extern	int	NRAD;
extern	int	NSEC;
extern	real	RMIN;
extern	real	RMAX;
extern	real	THICKNESSSMOOTHING;
extern	real	ROCHESMOOTHING;
extern	real	ASPECTRATIO;
extern	real	DASPECTRATIO;
extern	real	VISCOSITY;
extern	real	ALPHAVISCOSITY;
extern	real	DVISCOSITY;
extern	real	DALPHAVISCOSITY;
extern	real	SIGMASLOPE;
extern	real	RELEASERADIUS;
extern	real	RELEASEDATE;
extern	real	OMEGAFRAME;
extern	char	DISK[512];
extern	char	FRAME[512];
extern	char	OUTERSOURCEMASS[512];
extern	char	WRITEDENSITY[512];
extern	char	WRITEVELOCITY[512];
extern	char	INDIRECTTERM[512];
extern	char	EXCLUDEHILL[512];
extern	real	IMPOSEDDISKDRIFT;
extern	real	FLARINGINDEX;
extern	real	DFLARINGINDEX;
extern	real	ECCENTRICITY;
extern	real	CAVITYRADIUS;
extern	real	CAVITYRATIO;
extern	real	CAVITYWIDTH;
extern	real	TRANSITIONRADIUS;
extern	real	TRANSITIONRATIO;
extern	real	TRANSITIONWIDTH;
extern	real	LAMBDADOUBLING;
extern	int	ADDM;
extern	real	RIN;
extern	real	ROUT;
extern	int	NELSONBOUND;
extern	int	NELSONBOUNDD;
extern	real	ACCTIME;
extern	real	MASSTIME;
extern	real	FEELTIME;
extern	real	FEELTIMEE;
extern	int	SFTA;
extern	real	DENSITYFLOOR;
