int CPU_Rank;
int CPU_Number;
boolean CPU_Master, IAmTheFirst, IAmTheLast;
int IMIN;
int IMAX;
int Zero_or_active;
int Max_or_active;
int One_or_active;
int MaxMO_or_active;		/* MO: Minus One */
int GLOBALNRAD;
int NRAD1D, IINNER;
real Rinf[MAX1D], Rsup[MAX1D], Rmed[MAX1D], Surf[MAX1D];
real InvRmed[MAX1D], InvSurf[MAX1D], InvDiffRmed[MAX1D];
real InvDiffRsup[MAX1D], InvRinf[MAX1D], Radii[MAX1D], GlobalRmed[MAX1D];
real Rinf1D[MAX1D], Rsup1D[MAX1D], Rmed1D[MAX1D], Surf1D[MAX1D];
real InvRmed1D[MAX1D], InvSurf1D[MAX1D], InvDiffRmed1D[MAX1D];
real InvDiffRsup1D[MAX1D], InvRinf1D[MAX1D], Radii1D[MAX1D], GlobalRmed1D[MAX1D];
real SigmaMed1D[MAX1D], SigmaInf1D[MAX1D], MassTaper;
real SigmaMed[MAX1D], SigmaInf[MAX1D];
real Cosinus[MAX1D], Sinus[MAX1D];
real OmegaFrame, PhysicalTime;
int TimeStep;
real SOUNDSPEED[MAX1D];
real SOUNDSPEED1D[MAX1D];
real GLOBAL_SOUNDSPEED[MAX1D];
boolean Merge, AdvecteLabel, FakeSequential, MonitorIntegral, debug, OnlyInit;
boolean	GotoNextOutput, StoreSigma, ViscosityAlpha, RocheSmoothing;
boolean CentrifugalBalance, ExcludeHill, SloppyCFL;
MPI_Status stat;
PolarGrid *CellAbscissa, *CellOrdinate;
PolarGrid *RhoStar, *RhoInt, *Potential;
PolarGrid1D *RhoStar1D, *RhoInt1D, *Potential1D;
PolarGrid *Potplanet;
boolean LogGrid;
boolean OverridesOutputdir;
char NewOutputdir[1024];
