/** \file param_noex.h

Created automatically during compilation
from var.c. Do not edit. See Perl script
"varparser.pl" for details.
*/
real	DT;
real	SIGMA0;
int	NINTERM;
int	NTOT;
char	OUTPUTDIR[512];
char	OPENINNERBOUNDARY[512];
char	ADVLABEL[512];
char	TRANSPORT[512];
char	DUSTDIFF[512];
char	GASDCOUPLE[512];
char	DUSTIMPLICIT[512];
real	COUPLEINN;
real	DUSTDIFFINN;
real	PSize;
char	PLANETCONFIG[512];
real	MASSTAPER;
char	GRIDSPACING[512];
int	NRAD;
int	NSEC;
real	RMIN;
real	RMAX;
real	THICKNESSSMOOTHING;
real	ROCHESMOOTHING;
real	ASPECTRATIO;
real	DASPECTRATIO;
real	VISCOSITY;
real	ALPHAVISCOSITY;
real	DVISCOSITY;
real	DALPHAVISCOSITY;
real	SIGMASLOPE;
real	RELEASERADIUS;
real	RELEASEDATE;
real	OMEGAFRAME;
char	DISK[512];
char	FRAME[512];
char	OUTERSOURCEMASS[512];
char	WRITEDENSITY[512];
char	WRITEVELOCITY[512];
char	INDIRECTTERM[512];
char	EXCLUDEHILL[512];
real	IMPOSEDDISKDRIFT;
real	FLARINGINDEX;
real	DFLARINGINDEX;
real	ECCENTRICITY;
real	CAVITYRADIUS;
real	CAVITYRATIO;
real	CAVITYWIDTH;
real	TRANSITIONRADIUS;
real	TRANSITIONRATIO;
real	TRANSITIONWIDTH;
real	LAMBDADOUBLING;
int	ADDM;
real	RIN;
real	ROUT;
int	NELSONBOUND;
int	NELSONBOUNDD;
real	ACCTIME;
real	MASSTIME;
real	FEELTIME;
real	FEELTIMEE;
int	SFTA;
real	DENSITYFLOOR;
