/** \file var.c

Contains the function that connects the string of the parameter file to global variables.
The var() function is found in Interpret.c

*/

#define __LOCAL
#include "fargo.h"
#undef __LOCAL

void
InitVariables()
{
  var("DT", &DT, REAL, YES, "1.");
  var("SIGMA0", &SIGMA0, REAL, YES, "173.");
  var("NINTERM", &NINTERM, INT, YES, "10.");
  var("NTOT", &NTOT, INT, YES, "1501.");
  var("OUTPUTDIR", OUTPUTDIR, STRING, YES, "~masset");
  var("INNERBOUNDARY", OPENINNERBOUNDARY, STRING, NO, "WALL");
  var("LABELADVECTION", ADVLABEL, STRING, NO, "NO");
  var("TRANSPORT", TRANSPORT, STRING, NO, "FAST");
  var("DUSTDIFF", DUSTDIFF, STRING, NO, "NO");
  var("GASDCOUPLE", GASDCOUPLE, STRING, NO, "NO");
  var("DUSTIMPLICIT", DUSTIMPLICIT, STRING, NO, "NO");
  var("COUPLEINN", &COUPLEINN, REAL, NO, "0.0");
  var("DUSTDIFFINN", &DUSTDIFFINN, REAL, NO, "0.0");
  var("PSIZE", &PSize, REAL, YES, "1.");
  var("PLANETCONFIG", PLANETCONFIG, STRING, NO, "Systems/SolarSystem.cfg");
  var("MASSTAPER", &MASSTAPER, REAL, NO, "0.0000001");
  var("RADIALSPACING", GRIDSPACING, STRING, NO, "ARITHMETIC");
  var("NRAD", &NRAD, INT, YES, "64.0");
  var("NSEC", &NSEC, INT, YES, "64.0");
  var("RMIN", &RMIN, REAL, YES, "1.0");
  var("RMAX", &RMAX, REAL, YES, "1.0");
  var("THICKNESSSMOOTHING", &THICKNESSSMOOTHING, REAL, NO, "0.0");
  var("ROCHESMOOTHING", &ROCHESMOOTHING, REAL, NO, "0.0");
  var("ASPECTRATIO", &ASPECTRATIO, REAL, YES, "0.05");
  var("DASPECTRATIO", &DASPECTRATIO, REAL, YES, "0.05");
  var("VISCOSITY", &VISCOSITY, REAL, NO, "0.0");  
  var("ALPHAVISCOSITY", &ALPHAVISCOSITY, REAL, NO, "0.0");  
  var("DVISCOSITY", &DVISCOSITY, REAL, NO, "0.0");
  var("DALPHAVISCOSITY", &DALPHAVISCOSITY, REAL, NO, "0.0");
  var("SIGMASLOPE", &SIGMASLOPE, REAL, YES, "0.0");  
  var("RELEASERADIUS", &RELEASERADIUS, REAL, NO, "0.0");  
  var("RELEASEDATE", &RELEASEDATE, REAL, NO, "0.0");  
  var("OMEGAFRAME", &OMEGAFRAME, REAL, NO, "0.0");
  var("DISK", DISK, STRING, NO, "YES");
  var("FRAME", FRAME, STRING, NO, "FIXED");
  var("OUTERSOURCEMASS", OUTERSOURCEMASS, STRING, NO, "NO");
  var("WRITEDENSITY", WRITEDENSITY, STRING, NO, "YES");
  var("WRITEVELOCITY", WRITEVELOCITY, STRING, NO, "YES");
  var("INDIRECTTERM", INDIRECTTERM, STRING, NO, "YES");
  var("EXCLUDEHILL", EXCLUDEHILL, STRING, NO, "NO");
  var("IMPOSEDDISKDRIFT", &IMPOSEDDISKDRIFT, REAL, NO, "0.0");
  var("FLARINGINDEX", &FLARINGINDEX, REAL, NO, "0.0");
  var("DFLARINGINDEX", &DFLARINGINDEX, REAL, NO, "0.0");
  var("ECCENTRICITY", &ECCENTRICITY, REAL, NO, "0.0");
  var("CAVITYRADIUS", &CAVITYRADIUS, REAL, NO, "0.0");
  var("CAVITYRATIO", &CAVITYRATIO, REAL, NO, "1.0");
  var("CAVITYWIDTH", &CAVITYWIDTH, REAL, NO, "1.0");
  var("TRANSITIONRADIUS", &TRANSITIONRADIUS, REAL, NO, "0.0");
  var("TRANSITIONRATIO", &TRANSITIONRATIO, REAL, NO, "1.0");
  var("TRANSITIONWIDTH", &TRANSITIONWIDTH, REAL, NO, "1.0");
  var("LAMBDADOUBLING", &LAMBDADOUBLING, REAL, NO, "0.0");
  // Fargo Dust Variables
  var("ADDM", &ADDM, INT, NO, "0");
  var("RIN", &RIN, REAL, NO, "0.0");
  var("ROUT", &ROUT, REAL, NO, "1000000.0");
  var("NELSONBOUND", &NELSONBOUND, INT, NO, "0");
  var("NELSONBOUNDD", &NELSONBOUNDD, INT, NO, "0");
  var("ACCTIME", &ACCTIME, REAL, NO, "0.0");
  var("MASSTIME", &MASSTIME, REAL, NO, "0.0");
  var("FEELTIME", &FEELTIME, REAL, NO, "0.0");
  var("FEELTIMEE", &FEELTIMEE, REAL, NO, "0.0");
  var("SFTA", &SFTA, INT, NO, "0");
  var("DENSITYFLOOR", &DENSITYFLOOR, REAL, NO, "0.0");
  // New Variables
  var("FAKEACCRETION", FAKEACCRETION, STRING, NO, "YES");
  var("TAPERPROFILE", TAPERPROFILE, STRING, NO, "YES");
  var("INNERFOLDNUMBER", &INNERFOLDNUMBER, REAL, NO, "3.0");
  var("OUTERFOLDNUMBER", &OUTERFOLDNUMBER, REAL, NO, "500.0");
  // Newer Variables --- for vortex dust diffusion
  var("VORTEXDIFFUSION", VORTEXDIFFUSION, STRING, NO, "NO");
  var("VORTEXDIFFUSIONCOEFFICIENT", &VORTEXDIFFUSIONCOEFFICIENT, REAL, NO, "0.001");
  var("VORTEXDIFFUSIONBACKGROUND", &VORTEXDIFFUSIONBACKGROUND, REAL, NO, "-1");
  var("VORTEXDIFFUSIONTHRESHOLD", &VORTEXDIFFUSIONTHRESHOLD, REAL, NO, "2.0");
  var("VORTEXDIFFUSIONLOWERTHRESHOLD", &VORTEXDIFFUSIONLOWERTHRESHOLD, REAL, NO, "1.5");
  var("VORTEXDIFFIN", &VORTEXDIFFIN, REAL, NO, "1.0");
  var("VORTEXDIFFOUT", &VORTEXDIFFOUT, REAL, NO, "2.5");
  var("DIFFUSIONTIME", &DIFFUSIONTIME, REAL, NO, "0.0");
  // Made Gas-to-Dust Ratio a Parameter
  var("GASTODUSTRATIO", &GASTODUSTRATIO, REAL, NO, "100.0");
  // CFL Variables
  var("CFLIN", &CFLIN, REAL, NO, "0.0");
  var("CFLOUT", &CFLOUT, REAL, NO, "100000.0");
  var("GASCFL", GASCFL, STRING, NO, "NO");
  // Extra Files
  var("EXTRAFILES", EXTRAFILES, STRING, NO, "NO");
  // Dead Zone Variables
  var("DEADZONE", DEADZONE, STRING, NO, "NO");
  var("FULLDEADZONE", FULLDEADZONE, STRING, NO, "NO");
  var("DEADZONERADIUS", &DEADZONERADIUS, REAL, NO, "1.5");
  var("DEADZONEWIDTH", &DEADZONEWIDTH, REAL, NO, "0.08");
  var("INNERDEADZONERADIUS", &INNERDEADZONERADIUS, REAL, NO, "1.0");
  var("INNERDEADZONEWIDTH", &INNERDEADZONEWIDTH, REAL, NO, "0.05");
  var("VISCOSITYRATIO", &VISCOSITYRATIO, REAL, NO, "0.01");
  // Evolving Dead Zone Variables
  var("EVOLVINGDEADZONE", EVOLVINGDEADZONE, STRING, NO, "NO");
  var("EVOLVINGDEADZONETHRESHOLD", &EVOLVINGDEADZONETHRESHOLD, REAL, NO, "0.5"); // At 20 AU, Sigma0 = 30 g, 
  var("EVOLVINGDEADZONEWIDTH", &EVOLVINGDEADZONEWIDTH, REAL, NO, "0.16667");
  // Maximum Stokes number (to make SFTA work in planet gap)
  var("MAXSTOKESNUMBER", &MAXSTOKESNUMBER, REAL, NO, "100000.0");
}

